-- Measure by Dimesnsio

--Total Sales By Country
--Total Quantity By Category
--Average Price By Product
--Total orders By customer

-- Find Total customers by countries
SELECT
    country,
    COUNT(*) total_customers
FROM gold.dim_customers
GROUP BY country
-- Find total customers by gender
SELECT
    gender,
    COUNT(*) customer_by_gender
FROM gold.dim_customers
GROUP BY gender
-- Find total Product by Category
SELECT 
    category,
    COUNT(*) 
FROM gold.dim_products
GROUP BY category
-- What is the Average costs in each Category?
SELECT 
    category,
    AVG(cost) avg_cost_by_category
FROM gold.dim_products
GROUP BY category
-- what is total revenue generated by each customer

SELECT 
    c.firstname,
    SUM(f.sales_amount) AS total_sales_by_customer
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY 
    f.customer_key,
    c.firstname
ORDER BY 
    total_sales_by_customer DESC;


-- what is the distribution of sold items across countries
SELECT 
    c.country,
    SUM(f.quantity) AS total_items_sold,
    ROUND(100.0 * SUM(f.quantity) / SUM(SUM(f.quantity)) OVER(), 2) AS percentage_share
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
    ON f.customer_key = c.customer_key
GROUP BY 
    c.country
ORDER BY 
    total_items_sold DESC;

SELECT * FROM gold.fact_sales
